version: "3.5"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  api01: &api
    build:
      context: .
      target: development
    environment:
      - PORT=3000
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"

  api02:
    <<: *api
